const c=document.getElementById('game'),x=c.getContext('2d');let W,H,dpr,player={x:0,y:0,a:0},bullets=[],bots=[],particles=[],score=0,ammo=30,time=90,round=1,playing=true;const keys={};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;c.style.width=W+'px';c.style.height=H+'px';x.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const rand=(a,b)=>a+Math.random()*(b-a);function spawn(){bots=[];for(let i=0;i<7+round;i++)bots.push({x:rand(-700,700),y:rand(-450,450),hp:100,a:0,s:rand(0,1)>.5?1:-1})}spawn();
function world(){x.fillStyle='#14231d';x.fillRect(0,0,W,H);x.save();x.translate(W/2-player.x,H/2-player.y);x.strokeStyle='#20372e';x.lineWidth=2;for(let i=-1600;i<1600;i+=80){x.beginPath();x.moveTo(i,-1000);x.lineTo(i,1000);x.stroke();x.beginPath();x.moveTo(-1600,i);x.lineTo(1600,i);x.stroke()}x.fillStyle='#1b3028';for(let i=-700;i<700;i+=280)for(let j=-450;j<450;j+=260)x.fillRect(i+20,j+30,180,100);x.restore()}
function drawSoldier(o,col,me=false){x.save();x.translate(W/2+o.x-player.x,H/2+o.y-player.y);x.rotate(o.a);x.fillStyle='rgba(0,0,0,.3)';x.beginPath();x.ellipse(0,14,19,10,0,0,7);x.fill();x.fillStyle=col;x.beginPath();x.arc(0,0,16,0,7);x.fill();x.fillStyle='#d7b38b';x.beginPath();x.arc(0,-3,8,0,7);x.fill();x.fillStyle='#303a37';x.fillRect(5,-4,27,6);x.restore()}
function shoot(){if(!playing||ammo<=0)return;ammo--;document.getElementById('ammo').textContent=ammo;bullets.push({x:player.x+Math.cos(player.a)*25,y:player.y+Math.sin(player.a)*25,a:player.a,life:0});for(const b of bots){const dx=b.x-player.x,dy=b.y-player.y;if(Math.abs(Math.atan2(dy,dx)-player.a)<.08&&Math.hypot(dx,dy)<900){b.hp-=50;if(b.hp<=0){score++;document.getElementById('score').textContent=score;for(let i=0;i<12;i++)particles.push({x:b.x,y:b.y,vx:rand(-2,2),vy:rand(-2,2),l:30});b.x=9999}}}}
function reload(){ammo=30;document.getElementById('ammo').textContent=ammo}
function update(){if(!playing)return;let speed=3;let sx=0,sy=0;if(keys.w||keys.ArrowUp)sy-=1;if(keys.s||keys.ArrowDown)sy+=1;if(keys.a||keys.ArrowLeft)sx-=1;if(keys.d||keys.ArrowRight)sx+=1;let n=Math.hypot(sx,sy)||1;player.x+=sx/n*speed;player.y+=sy/n*speed;for(const b of bots){if(b.x>9000)continue;let dx=player.x-b.x,dy=player.y-b.y;b.a=Math.atan2(dy,dx);b.x+=Math.cos(b.a)*.45;b.y+=Math.sin(b.a)*.45}for(const q of bullets){q.x+=Math.cos(q.a)*18;q.y+=Math.sin(q.a)*18;q.life++}bullets=bullets.filter(q=>q.life<60);particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.l--});particles=particles.filter(p=>p.l>0);time-=1/60;if(time<=0){time=90;round++;spawn();}document.getElementById('timer').textContent=`${String(Math.ceil(time/60)).padStart(2,'0')}:${String(Math.ceil(time%60)).padStart(2,'0')}`;}
function draw(){world();for(const b of bullets){x.fillStyle='#ffd36a';x.beginPath();x.arc(W/2+b.x-player.x,H/2+b.y-player.y,3,0,7);x.fill()}for(const b of bots)if(b.x<9000)drawSoldier(b,'#c94c4c');drawSoldier(player,'#65c98b',true);for(const p of particles){x.fillStyle='#d9a56b';x.fillRect(W/2+p.x-player.x,H/2+p.y-player.y,3,3)}requestAnimationFrame(()=>{update();draw()})}draw();
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key==='r')reload();if(e.code==='Space')shoot()});addEventListener('keyup',e=>keys[e.key]=false);document.getElementById('fire').addEventListener('pointerdown',shoot);document.getElementById('reload').addEventListener('pointerdown',reload);document.getElementById('nextRound').onclick=()=>{document.getElementById('roundEnd').style.display='none';playing=true;spawn()};
function stick(el,cb){let sx=0,sy=0,active=false;const move=e=>{if(!active)return;const r=el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,len=Math.min(Math.hypot(dx,dy),r.width*.38),a=Math.atan2(dy,dx);el.querySelector('.stick').style.transform=`translate(${Math.cos(a)*len}px,${Math.sin(a)*len}px)`;cb(dx/r.width*2,dy/r.height*2)};el.onpointerdown=e=>{active=true;el.setPointerCapture(e.pointerId);move(e)};el.onpointermove=move;el.onpointerup=()=>{active=false;el.querySelector('.stick').style.transform='';cb(0,0)}}stick(document.getElementById('joystick'),(a,b)=>{keys.w=b<-.15;keys.s=b>.15;keys.a=a<-.15;keys.d=a>.15});stick(document.getElementById('aim'),(a,b)=>{if(Math.hypot(a,b)>.15)player.a=Math.atan2(b,a)});
let deferred;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;document.getElementById('install').style.display='flex'});document.getElementById('installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};document.getElementById('closeInstall').onclick=()=>document.getElementById('install').style.display='none';
